// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import AudioPlaybackController from "./audio_playback_controller";
application.register("audio-playback", AudioPlaybackController);

import AudioStreamController from "./audio_stream_controller";
application.register("audio-stream", AudioStreamController);

import ChatController from "./chat_controller";
application.register("chat", ChatController);

import ConversationController from "./conversation_controller";
application.register("conversation", ConversationController);

import DropdownController from "./dropdown_controller";
application.register("dropdown", DropdownController);

import LanguageController from "./language_controller";
application.register("language", LanguageController);

import NavbarController from "./navbar_controller";
application.register("navbar", NavbarController);
